"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
import { ArrowDownToLine,FileText,LockKeyhole,ShieldCheck } from "lucide-react";
type Meta={asset:{name:string;fileName:string;contentType:string;size:number};link:{requireEmail:boolean;allowDownload:boolean;expiresAt:string|null}};
export default function ShareViewer({id}:{id:string}){const[meta,setMeta]=useState<Meta|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(""),[error,setError]=useState(""),[granted,setGranted]=useState(false),started=useRef(Date.now());
 useEffect(()=>{fetch(`/api/public/share/${id}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setMeta(j);setLoading(false);if(!j.link.requireEmail)await grant("")}).catch(e=>{setError(e.message);setLoading(false)})},[id]);
 useEffect(()=>{if(!granted)return;const send=()=>{const durationMs=Date.now()-started.current;fetch(`/api/public/share/${id}/track`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"heartbeat",durationMs,progress:Math.min(95,Math.round(durationMs/3000))}),keepalive:true}).catch(()=>{})};const timer=setInterval(send,15000);return()=>{clearInterval(timer);send()}},[granted,id]);
 async function grant(value:string){const r=await fetch(`/api/public/share/${id}/access`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:value})}),j=await r.json();if(!r.ok){setError(j.error);return}setGranted(true);setError("")}
 async function submit(e:FormEvent){e.preventDefault();await grant(email)}
 function download(){fetch(`/api/public/share/${id}/track`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"download",durationMs:Date.now()-started.current,progress:100}),keepalive:true}).catch(()=>{})}
 if(loading)return <main className="viewer-shell"><div className="viewer-card">Preparing document…</div></main>;
 if(error&&!meta)return <main className="viewer-shell"><div className="viewer-card unavailable"><LockKeyhole/><h1>Link unavailable</h1><p>{error}</p></div></main>;
 if(!meta)return null;
 if(!granted)return <main className="viewer-shell"><div className="viewer-brand"><span>A</span>Assetly</div><div className="gate-card"><div className="doc-badge"><FileText/></div><p className="eyebrow">Shared with you</p><h1>{meta.asset.name}</h1><p>Enter your work email to view this document.</p><form onSubmit={submit}><label htmlFor="visitor-email">Work email</label><input id="visitor-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/><button type="submit">View document</button>{error&&<span className="form-error">{error}</span>}</form><div className="privacy"><ShieldCheck/>Your email is shared only with the document owner.</div></div></main>;
 const pdf=meta.asset.contentType==="application/pdf";
 return <main className="document-shell"><header className="document-header"><div className="viewer-brand"><span>A</span>Assetly</div><div className="document-title"><FileText/><div><b>{meta.asset.name}</b><small>{meta.asset.fileName}</small></div></div>{meta.link.allowDownload?<a href={`/api/public/share/${id}/file?download=1`} onClick={download} className="download-button"><ArrowDownToLine/>Download</a>:<span className="download-disabled"><LockKeyhole/>View only</span>}</header><section className="document-stage">{pdf?<iframe title={meta.asset.name} src={`/api/public/share/${id}/file#toolbar=0`}/>:<div className="unsupported-view"><FileText/><h2>{meta.asset.name}</h2><p>This file is available through its original application format.</p>{meta.link.allowDownload&&<a href={`/api/public/share/${id}/file?download=1`} onClick={download}>Download file</a>}</div>}</section></main>
}
