"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { OrganizationSwitcher, UserButton, useAuth } from "@clerk/nextjs";
import { uploadPresigned } from "@vercel/blob/client";
import { BarChart3,Copy,Eye,FileText,FolderOpen,Link2,Menu,MoreHorizontal,Plus,RefreshCw,Search,ShieldCheck,Upload,Users,X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { toast,Toaster } from "sonner";
type Asset={id:string;name:string;fileName:string;size:number;contentType:string;createdAt:string;views:number;visitors:number;links:number};
type LinkRow={id:string;assetId:string;assetName:string;label:string|null;requireEmail:boolean;allowDownload:boolean;expiresAt:string|null;revokedAt:string|null;createdAt:string};
type EventRow={id:string;email:string|null;event:string;durationMs:number|null;progress:number|null;createdAt:string;assetName:string;linkLabel:string|null;country:string|null};
type Analytics={summary:{views:number;visitors:number;avgDuration:number;avgProgress:number};recent:EventRow[]};
const BASE_PATH="/asset-access";
const emptyAnalytics={summary:{views:0,visitors:0,avgDuration:0,avgProgress:0},recent:[]};
function formatSize(n:number){return n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`}
function formatDate(v:string){return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))}
function formatDuration(n:number){const sec=Math.round(n/1000);return sec<60?`${sec}s`:`${Math.floor(sec/60)}m ${sec%60}s`}
export default function Home(){const{userId,orgId}=useAuth(),tenantId=orgId||userId;const[view,setView]=useState<"assets"|"links"|"analytics"|"visitors">("assets"),[assets,setAssets]=useState<Asset[]>([]),[links,setLinks]=useState<LinkRow[]>([]),[analytics,setAnalytics]=useState<Analytics>(emptyAnalytics),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[uploadOpen,setUploadOpen]=useState(false),[shareAsset,setShareAsset]=useState<Asset|null>(null),[mobile,setMobile]=useState(false),[uploading,setUploading]=useState(false);
 async function load(){setLoading(true);const[a,l,n]=await Promise.all([fetch(`${BASE_PATH}/api/assets`),fetch(`${BASE_PATH}/api/links`),fetch(`${BASE_PATH}/api/analytics`)]);if([a,l,n].some(r=>r.status===401)){toast.error("Your session has expired");setLoading(false);return}const[aj,lj,nj]=await Promise.all([a.json(),l.json(),n.json()]);setAssets(aj.assets||[]);setLinks(lj.links||[]);setAnalytics(nj.summary?nj:emptyAnalytics);setLoading(false)}
 useEffect(()=>{if(tenantId)load().catch(()=>{toast.error("Could not load workspace");setLoading(false)})},[tenantId]);
 const filtered=useMemo(()=>assets.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())),[assets,query]);
 async function uploadAssets(files:FileList|null){
  if(!files?.length)return;
  if(!tenantId){toast.error("Choose a workspace before uploading");return;}
  setUploading(true);
  let success=0;
  for(const file of Array.from(files)){
    try{
      const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");
      const pathname=`tenants/${tenantId}/assets/${crypto.randomUUID()}/${safe}`;
      const blob=await uploadPresigned(pathname,file,{access:"private",handleUploadUrl:`${BASE_PATH}/api/assets/upload`,multipart:file.size>10*1024*1024});
      const r=await fetch(`${BASE_PATH}/api/assets`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:file.name.replace(/\.[^/.]+$/,""),fileName:file.name,objectKey:blob.url,contentType:file.type||"application/octet-stream",size:file.size})});
      const j=await r.json();
      if(r.ok)success++;else toast.error(j.error||`Could not register ${file.name}`);
    }catch(error){toast.error(error instanceof Error?error.message:`Could not upload ${file.name}`)}
  }
  setUploading(false);
  if(success){toast.success(`${success} asset${success>1?"s":""} uploaded`);setUploadOpen(false);await load()}
}
 async function archive(a:Asset){const r=await fetch(`${BASE_PATH}/api/assets/${a.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({archive:true})});if(r.ok){toast.success("Asset archived");await load()}else toast.error("Could not archive asset")}
 async function revoke(link:LinkRow){const r=await fetch(`${BASE_PATH}/api/links/${link.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({revoke:!link.revokedAt})});if(r.ok){toast.success(link.revokedAt?"Link restored":"Link revoked");await load()}else toast.error("Could not update link")}
 async function copy(path:string){await navigator.clipboard.writeText(`${location.origin}${path}`);toast.success("Link copied")}
 const nav=[["assets","Assets",FolderOpen],["links","Links",Link2],["analytics","Analytics",BarChart3],["visitors","Visitors",Users]] as const;
 return <div className="app-shell"><aside className={`sidebar ${mobile?"mobile-open":""}`}><div className="brand"><div className="brand-mark">A</div><span>Assetly</span><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div><nav>{nav.map(([key,label,Icon])=><button key={key} className={`nav-item ${view===key?"active":""}`} onClick={()=>{setView(key);setMobile(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="security-panel"><ShieldCheck/><div><b>Private workspace</b><span>Files are access-controlled</span></div></div><div className="profile"><OrganizationSwitcher afterCreateOrganizationUrl={BASE_PATH} afterSelectOrganizationUrl={BASE_PATH}/></div><div className="profile"><UserButton afterSignOutUrl={`${BASE_PATH}/sign-in`} showName/></div></div></aside>
 <main className="content"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div><p>Workspace</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="header-actions"><Button variant="ghost" size="icon" onClick={load} aria-label="Refresh workspace"><RefreshCw size={17}/></Button>{view==="assets"&&<><div className="search"><Search size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets"/></div><Dialog open={uploadOpen} onOpenChange={setUploadOpen}><DialogTrigger asChild><Button className="primary"><Plus size={17}/>Add asset</Button></DialogTrigger><DialogContent className="upload-dialog"><DialogHeader><DialogTitle>Add an asset</DialogTitle><DialogDescription>Upload PDFs, presentations, documents, or videos up to 500 MB.</DialogDescription></DialogHeader><label className={`dropzone ${uploading?"busy":""}`}><Upload size={28}/><strong>{uploading?"Uploading securely…":"Drop files here or click to browse"}</strong><span>Files are private until you create a link.</span><input disabled={uploading} type="file" multiple accept=".pdf,.pptx,.docx,.mp4,.mov,.webm,application/pdf,video/*" onChange={e=>uploadAssets(e.target.files)}/></label></DialogContent></Dialog></>}</div></header>
 {loading?<Loading/>:view==="assets"?<Assets assets={filtered} query={query} onShare={setShareAsset} onArchive={archive} onAdd={()=>setUploadOpen(true)}/>:view==="links"?<Links links={links} onCopy={copy} onRevoke={revoke}/>:view==="analytics"?<AnalyticsView data={analytics}/>:<VisitorsView events={analytics.recent}/>}</main>
 <ShareDialog asset={shareAsset} onClose={()=>setShareAsset(null)} onCreated={async(path)=>{await copy(path);setShareAsset(null);await load()}}/><Toaster position="bottom-right" richColors/></div>
}
function Loading(){return <div className="loading-grid">{[1,2,3,4].map(x=><div key={x} className="skeleton-card"/>)}</div>}
function Empty({title,copy,action}:{title:string;copy:string;action?:()=>void}){return <div className="empty-state"><div><FileText/></div><h2>{title}</h2><p>{copy}</p>{action&&<Button className="primary" onClick={action}><Plus/>Add your first asset</Button>}</div>}
function Assets({assets,query,onShare,onArchive,onAdd}:{assets:Asset[];query:string;onShare:(a:Asset)=>void;onArchive:(a:Asset)=>void;onAdd:()=>void}){if(!assets.length)return <Empty title={query?"No matching assets":"Your asset library is empty"} copy={query?"Try a different search.":"Upload a document, then create a trackable link for a prospect."} action={query?undefined:onAdd}/>;return <><section className="overview-grid compact"><Metric label="Assets" value={String(assets.length)}/><Metric label="Total views" value={String(assets.reduce((n,a)=>n+Number(a.views),0))}/><Metric label="Unique visitors" value={String(assets.reduce((n,a)=>n+Number(a.visitors),0))}/><Metric label="Active links" value={String(assets.reduce((n,a)=>n+Number(a.links),0))}/></section><div className="asset-table"><div className="table-head"><span>Asset</span><span>Views</span><span>Visitors</span><span>Links</span><span/></div>{assets.map(a=><div className="asset-row" key={a.id}><div className="asset-name"><div className="thumb slate">{a.name.slice(0,2).toUpperCase()}</div><div><b>{a.name}</b><span>{a.fileName.split(".").pop()?.toUpperCase()} · {formatSize(a.size)} · {formatDate(a.createdAt)}</span></div></div><div className="stat-cell"><b>{a.views}</b></div><div className="stat-cell"><b>{a.visitors}</b></div><div className="stat-cell"><b>{a.links}</b></div><div className="row-actions"><Button variant="outline" size="sm" onClick={()=>onShare(a)}><Link2 size={15}/>Share</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`More actions for ${a.name}`}><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>onShare(a)}>Create link</DropdownMenuItem><DropdownMenuItem onClick={()=>onArchive(a)}>Archive asset</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>)}</div></>}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<em>{sub}</em>}</div>}
function Links({links,onCopy,onRevoke}:{links:LinkRow[];onCopy:(p:string)=>void;onRevoke:(l:LinkRow)=>void}){if(!links.length)return <Empty title="No share links yet" copy="Create a link from an asset to track engagement by prospect or campaign."/>;return <div className="link-list">{links.map(l=><article className="link-card" key={l.id}><div className="link-icon"><Link2/></div><div><div className="link-title"><b>{l.label||l.assetName}</b>{l.revokedAt&&<span className="status revoked">Revoked</span>}{!l.revokedAt&&<span className="status live">Live</span>}</div><p>{l.assetName}</p><small>{l.requireEmail?"Email required":"Open access"} · {l.allowDownload?"Download allowed":"View only"}{l.expiresAt?` · Expires ${formatDate(l.expiresAt)}`:""}</small></div><div className="link-actions"><Button variant="outline" disabled={!!l.revokedAt} onClick={()=>onCopy(`${BASE_PATH}/share/${l.id}`)}><Copy/>Copy</Button><Button variant="ghost" onClick={()=>onRevoke(l)}>{l.revokedAt?"Restore":"Revoke"}</Button></div></article>)}</div>}
function AnalyticsView({data}:{data:Analytics}){return <><section className="overview-grid"><Metric label="Document opens" value={String(data.summary.views||0)}/><Metric label="Unique visitors" value={String(data.summary.visitors||0)}/><Metric label="Avg. engagement" value={formatDuration(data.summary.avgDuration||0)}/><Metric label="Avg. completion" value={`${Math.round(data.summary.avgProgress||0)}%`}/></section><div className="activity-list">{data.recent.length?data.recent.map(e=><Event event={e} key={e.id}/>):<Empty title="No engagement yet" copy="Activity will appear when a recipient opens a shared link."/ >}</div></>}
function VisitorsView({events}:{events:EventRow[]}){const latest=new Map<string,EventRow>();events.filter(e=>e.email).forEach(e=>{if(!latest.has(e.email!))latest.set(e.email!,e)});if(!latest.size)return <Empty title="No identified visitors" copy="Email-gated link visitors will appear here."/>;return <div className="visitor-grid">{[...latest.values()].map(e=><article className="visitor-card" key={e.email}><div className="visitor-avatar">{e.email?.slice(0,2).toUpperCase()}</div><div><b>{e.email}</b><p>{e.assetName}{e.linkLabel?` · ${e.linkLabel}`:""}</p><small>{e.country||"Location unavailable"} · Last active {formatDate(e.createdAt)}</small></div></article>)}</div>}
function Event({event:e}:{event:EventRow}){return <div className="activity-item"><div className="activity-icon"><Eye/></div><div><p><b>{e.email||"Anonymous visitor"}</b> {e.event==="open"?"opened":e.event==="download"?"downloaded":"viewed"} <strong>{e.assetName}</strong></p><span>{e.linkLabel||"Unlabeled link"}{e.durationMs?` · ${formatDuration(e.durationMs)}`:""}{e.progress?` · ${e.progress}%`:""}</span></div><time>{formatDate(e.createdAt)}</time></div>}
function ShareDialog({asset,onClose,onCreated}:{asset:Asset|null;onClose:()=>void;onCreated:(p:string)=>void}){const[label,setLabel]=useState(""),[requireEmail,setRequireEmail]=useState(true),[allowDownload,setAllowDownload]=useState(false),[expires,setExpires]=useState(""),[saving,setSaving]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!asset)return;setSaving(true);const r=await fetch(`${BASE_PATH}/api/links`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assetId:asset.id,label,requireEmail,allowDownload,expiresAt:expires||null})}),j=await r.json();setSaving(false);if(r.ok){toast.success("Trackable link created");onCreated(j.url)}else toast.error(j.error||"Could not create link")}return <Dialog open={!!asset} onOpenChange={o=>!o&&onClose()}><DialogContent className="share-dialog"><DialogHeader><DialogTitle>Share “{asset?.name}”</DialogTitle><DialogDescription>Create a separate link for each prospect or campaign so engagement stays attributable.</DialogDescription></DialogHeader><form className="share-form" onSubmit={submit}><label>Link label<Input value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Modern Automotive outreach"/></label><label className="check-row"><input type="checkbox" checked={requireEmail} onChange={e=>setRequireEmail(e.target.checked)}/><span><b>Require email</b><small>Identify each person who views the asset.</small></span></label><label className="check-row"><input type="checkbox" checked={allowDownload} onChange={e=>setAllowDownload(e.target.checked)}/><span><b>Allow download</b><small>Recipients can save the original file.</small></span></label><label>Expiration date<Input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label><Button className="primary" disabled={saving}>{saving?"Creating link…":"Create and copy link"}</Button></form></DialogContent></Dialog>}
